chart styling and axis samples json
IgniteUI/igniteui-xplat-examples pull request #10
Opened 2021-05-20 20:15 UTC by igMPeterson

chart styling and axis samples json

2021-05-20 22:43 UTC, HUSSAR-mtrela requested changes

2021-05-20 22:43 UTC, HUSSAR-mtrela commented on samples/charts/category-chart/axis-locations.json
> +      "xAxisInterval": 1
set yAxisLabelLocation to OutsideRight

2021-05-21 12:33 UTC, igMPeterson commented on samples/charts/category-chart/axis-locations.json
> +      "xAxisInterval": 1
added property in update

2021-05-21 18:28 UTC, HUSSAR-mtrela approved these changes

2021-05-21 18:28 UTC, merged

2021-05-24 13:05 UTC, igMPeterson commented
completed