Azure pipeline that uses the CodeExporterApp to convert samples & make PRs to destination git repos
IgniteUI/igniteui-xplat-examples pull request #197
Opened 2023-04-18 12:28 UTC by turbobobbytraykov

2023-04-18 14:23 UTC, HUSSAR-mtrela requested changes

2023-04-18 14:23 UTC, HUSSAR-mtrela commented on azure-pipelines/build-pipeline.yml
> +      ref: '$(Build.SourceBranch)'
for now, exclude exporting this repo to IgniteUIAngularExamples because our Angular template is not complete

2023-04-18 14:23 UTC, HUSSAR-mtrela commented on azure-pipelines/build-pipeline.yml
> +      codeExporterAppBranch: $(codeExporterAppBranch)
for now, exclude exporting this repo to IgniteUIAngularExamples because our Angular template is not complete

2023-04-18 14:24 UTC, HUSSAR-mtrela commented
@turbobobbytraykov see my comment above

2023-04-25 18:58 UTC, HUSSAR-mtrela requested changes

2023-04-25 18:58 UTC, HUSSAR-mtrela commented on azure-pipelines/dev-run-pipeline.yml
> +      #ref: vnext
@turbobobbytraykov I think this is a mistake to commente out vnext branch, right?

2023-05-02 12:15 UTC, turbobobbytraykov commented on azure-pipelines/dev-run-pipeline.yml
> +      #ref: vnext
@HUSSAR-mtrela , it was unintentional - fixed.

2023-05-02 14:05 UTC, HUSSAR-mtrela approved these changes

2023-05-02 14:05 UTC, merged