Doc related sample improvements
IgniteUI/igniteui-xplat-examples pull request #199
Opened 2023-04-20 11:31 UTC by MayaKirova

- Grid overview sample - remove pk column, add  a template as the topic around the sample mentions cell templating.
- Grid custom group by sample - remove it as custom group it's too custom and cannot be configured via the editor.  It also cannot be configured at all for Blazor, so there's be just a web component sample.

2023-04-25 19:13 UTC, HUSSAR-mtrela requested changes

2023-04-25 19:13 UTC, HUSSAR-mtrela commented on samples/grids/grid/groupby-custom.json
> +  "export": false,
please add a note in TODO section above with info why this sample should not be exported

2023-04-25 19:13 UTC, HUSSAR-mtrela commented on samples/grids/grid/clipboard-operations.json
> +  "export": false,
please add a note in TODO section above with info why this sample should not be exported

2023-06-27 10:52 UTC, skrustev approved these changes

2023-07-03 16:11 UTC, merged