Mdd toolbar set 1
IgniteUI/igniteui-xplat-examples pull request #205
Opened 2023-05-15 20:27 UTC by mddifilippo89

2023-05-16 22:03 UTC, HUSSAR-mtrela requested changes

2023-05-16 22:03 UTC, HUSSAR-mtrela commented on samples/charts/toolbar/layout-in-vertical-orientation.json
> +    "legendTitle": "Toolbar Theming and Styling"
remove the legendTitle because it is not needed here

2023-05-16 22:03 UTC, HUSSAR-mtrela commented on samples/charts/toolbar/actions-built-in-data-chart.json
> -      "targetRef": "chart"
how would toolbar know about the chart if it does not target it?

2023-05-16 22:03 UTC, HUSSAR-mtrela commented on samples/charts/toolbar/layout-in-vertical-orientation.json
> +  "note": "P2 show theming of Toolbar and targeted chart",
undo change on the note because this sample is about vertical orientation instead of theming.

2023-05-16 22:03 UTC, HUSSAR-mtrela commented on samples/charts/toolbar/theming.json
>      "legendTitle": "Toolbar Theming and Styling"
remove legendTitle

2023-05-17 00:01 UTC, mddifilippo89 commented on samples/charts/toolbar/actions-built-in-data-chart.json
> -      "targetRef": "chart"
I am not removing it, must be an error with this review changes window.

2023-05-17 00:05 UTC, mddifilippo89 commented on samples/charts/toolbar/actions-built-in-data-chart.json
> -      "targetRef": "chart"
I double checked the file and this isn't being removed. must be a mistake by the review checker

2023-05-17 00:05 UTC, mddifilippo89 commented on samples/charts/toolbar/layout-in-vertical-orientation.json
> +    "legendTitle": "Toolbar Theming and Styling"
done, replaced with extra note.

2023-05-17 00:05 UTC, mddifilippo89 commented on samples/charts/toolbar/theming.json
>      "legendTitle": "Toolbar Theming and Styling"
done

2023-05-17 14:18 UTC, HUSSAR-mtrela approved these changes

2023-05-17 14:19 UTC, merged