Check in enhanced interval, min max gap, and corner radius samples
IgniteUI/igniteui-xplat-examples pull request #22
Opened 2022-04-12 19:28 UTC by agoldenbaum

2022-04-14 13:02 UTC, HUSSAR-mtrela requested changes

2022-04-14 13:02 UTC, HUSSAR-mtrela commented on samples/charts/data-chart/axis-annotations-corner-radius.json
> +      "type": "DataChart",
this feature should be showcased on CategoryChart
ask Graham to add these props to CategoryChart if they are missing

2022-04-14 13:02 UTC, HUSSAR-mtrela commented on samples/charts/data-chart/axis-enhanced-intervals.json
> +      "type": "DataChart",
this feature should be showcased on CategoryChart
ask Graham to add these props to CategoryChart if they are missing

2022-04-14 13:02 UTC, HUSSAR-mtrela commented on samples/charts/data-chart/axis-min-max-gap.json
> +      "type": "DataChart",
this feature should be showcased on CategoryChart
ask Graham to add these props to CategoryChart if they are missing

2022-04-18 21:46 UTC, HUSSAR-mtrela requested changes

2022-04-18 21:46 UTC, HUSSAR-mtrela commented on samples/charts/data-chart/axis-enhanced-intervals.json
> +{
rename file to "axis-label-management.json"

2022-04-18 21:46 UTC, HUSSAR-mtrela commented on samples/charts/data-chart/axis-enhanced-intervals.json
> +    "content": {
add property editors to toggle axis "enhanced*" properties and other axis props listed in this [topic](https://github.com/IgniteUI/igniteui-xplat-docs/blob/vnext/doc/en/components/charts/features/chart-axis-options.md#axis-labels-management)

2022-04-19 19:59 UTC, agoldenbaum commented
![EnhancedIntervalSample](https://user-images.githubusercontent.com/18269063/164085844-6ef71d23-b106-4486-b69d-50fea7f7114a.PNG)
![LabelRotationSample](https://user-images.githubusercontent.com/18269063/164085846-ba23d00a-70f8-4e38-ad07-fcdf6bb24c29.PNG)

2022-04-19 20:01 UTC, HUSSAR-mtrela requested changes

2022-04-19 20:01 UTC, HUSSAR-mtrela commented on samples/charts/data-chart/axis-label-rotation.json
> +        }
add 2nd property editor to change autoMarginAndAngleUpdateMode property

2022-04-19 20:11 UTC, HUSSAR-mtrela approved these changes

2022-04-19 20:11 UTC, merged