Cell Editing Template Sample and Styling
IgniteUI/igniteui-xplat-examples pull request #227
Opened 2023-06-08 12:00 UTC by tishko0

2023-06-09 09:12 UTC, MayaKirova requested changes

2023-06-09 09:12 UTC, MayaKirova commented on samples/grids/grid/cell-eiditing-sample.txt
> +{
This file should be a .json file (not .txt file). There's a typo in the name of the file as well (eiditing).

Also since there is a bug with the select: https://github.com/IgniteUI/igniteui-angular/issues/13096
Maybe this sample should not be exported for now as it will not fully work.
I suggest we disable it with a todo note:

```
  "todo": [ "Waiting for select integration fix for issue: https://github.com/IgniteUI/igniteui-angular/issues/13096" ],
  "export": false
```
And enabled it when the issue is fixed.

2023-06-09 09:12 UTC, MayaKirova commented on samples/grids/grid/cell-editing-styling.json
> +      "onInit": ["WebGridCellEditingStyleTemplate"],
Since the selector in the style's use id, add an id for the grid that matches it:
```
"id": "grid" 
```

2023-06-15 10:29 UTC, MayaKirova commented on samples/grids/grid/cell-editing-styling.json
> +      "onInit": ["WebGridCellEditingStyleTemplate"],
Also I think the "onInit" should be outside the "descriptions" block, like in this sample:
https://github.com/IgniteUI/igniteui-xplat-examples/blob/vnext/samples/grids/grid/styling-custom-CSS.json#L5

2023-06-16 12:54 UTC, MayaKirova requested changes

2023-06-16 12:54 UTC, MayaKirova commented on samples/grids/grid/cell-editing-sample.json
> +      "id": "grid",
My original comment about the missing id was on the styling sample. This one does not necessarily need an id.

With this change on this sample, the sample no longer works.
It seems that if id is set, but name is not set for some reason the editor generates 2 ids in WC:
```
        <igc-grid
        auto-generate="false"
        id="grid"
        primary-key="name"
        name="grid1"
        id="grid1">
```
Which results in error:
![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/10397980/6545cbc0-8876-4a34-b6ff-ebf3e825c9da)

Seems to be an issue with the editor but in order for the sample to work move the id and name to the cell-editing-styling sample:
```
      "id": "grid",
      "name": "grid",
```

2023-06-16 12:54 UTC, MayaKirova commented on samples/grids/grid/cell-editing-sample.json
> +          "field": "race",
The properties in the data source generate with capital case, for example:
```
{
            Name: `Stredo`,
            Age: `244`,
            Alignment: `💜 Lawful evil`,
            Race: `👩 Human`,
            Class: `🎻 Bard`
        }
```

But the `field` in the column definitions are with lower case. That seems to cause a mismatch, so cells are empty:

![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/10397980/71cda9eb-977f-4932-aff4-c379916f61af)

All should be with capital case: "Race", "Class" etc.

2023-06-16 12:54 UTC, MayaKirova commented on samples/grids/grid/cell-editing-styling.json
> +      "dataRef": "NwindData",
Still needs id:
```
    "id": "grid",
    "name": "grid",
```

2023-07-06 17:19 UTC, HUSSAR-mtrela commented
@tishko0 can you fix above issues reported by @MayaKirova?

2023-10-02 16:30 UTC, HUSSAR-mtrela commented
@MayaKirova I merged your PR #326 into this PR so is this PR ready for merge into 23.2.x now or is still in DEV?

2023-10-02 17:49 UTC, tishko0 commented on samples/grids/grid/cell-editing-sample.json
> +      "id": "grid",
should be okay now

2023-10-03 08:55 UTC, MayaKirova approved these changes

2023-10-04 14:02 UTC, merged