add Tree Grid row pinning samples
IgniteUI/igniteui-xplat-examples pull request #245
Opened 2023-06-22 11:00 UTC by onlyexeption

2023-07-05 09:33 UTC, MayaKirova requested changes

2023-07-05 09:33 UTC, MayaKirova commented on samples/grids/tree-grid/row-pinning-drag.json
> +		"hidden": true,
If you remove this "hidden": true setting from all configurations the action strip will show.

2023-07-05 09:33 UTC, MayaKirova commented on samples/grids/tree-grid/row-pinning-drag.json
> +  "export": false,
Needs export:true to generate a sample for all of the configurations.

2023-07-07 12:13 UTC, MayaKirova requested changes

2023-07-07 12:13 UTC, MayaKirova commented on samples/grids/tree-grid/row-pinning-drag.json
> +    "add event handlers for row dragging",
Will need row drag handlers to show the full functionality. Also I don't think this sample is shown in the tree grid row pinning topic here: https://github.com/IgniteUI/igniteui-xplat-docs/pull/896
So if we want it to be shown it will also need some change to enable the related doc section.

2023-07-07 12:13 UTC, MayaKirova commented on samples/grids/tree-grid/row-pinning-extra-column.json
> +        "actionStrip": {
Since this sample shows custom UI via extra column I don't think there's need to also have the default action strip UI.

2023-07-07 12:13 UTC, MayaKirova commented on samples/grids/tree-grid/row-pinning-extra-column.json
> +            "width": "100px",
Maybe this column should be a bit bigger, because the pin indicator does not seem to fit for some of the cells:
![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/10397980/d91aabbc-a7be-442f-a57e-f4bd5ab3ca99)

2023-07-07 12:13 UTC, MayaKirova commented on samples/grids/tree-grid/row-pinning-options.json
> +        "type": "PropertyEditorPanel",
The editor that this generates does not seem to work. It throws an error:
![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/10397980/1ea23e34-5608-4211-9a5b-5ca582baca31)

But it's probably the same issue as the one for the base grid sample: https://infragistics.visualstudio.com/NetAdvantage/_workitems/edit/23526/

2023-07-07 12:13 UTC, MayaKirova commented on samples/grids/tree-grid/row-pinning-options.json
> +    "export": false,
This should probably be "export": true

2023-07-07 12:13 UTC, MayaKirova commented on samples/grids/tree-grid/row-pinning-options.json
> +        "rowDraggable": true,
Probably does not need row draggable.

2023-07-07 12:13 UTC, MayaKirova commented on samples/grids/tree-grid/row-pinning-style.json
> +        "rowDraggable": true,
Probably does not need row draggable.

2023-12-15 12:07 UTC, mddragnev commented
@MayaKirova The treegrid samples are disabled for react

2023-12-15 12:09 UTC, MayaKirova commented
@mddragnev @dkamburov  Yes. I think it is intentional since we've done no testing for the react tree grid. The docs are also disabled for react.

2023-12-15 12:15 UTC, mddragnev commented
@MayaKirova 
Blazor styling sample does not have styling
Also, for the row pinning options sample - we cannot set pinning to bottom

2023-12-15 13:31 UTC, MayaKirova commented
@mddragnev It does have styling if you pin a row:
![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/10397980/7137c37e-905b-4cb1-967a-d3208ff02be5)
Do you perhaps mean that there's no initial pinned row?

2023-12-15 14:07 UTC, mddragnev commented
@MayaKirova I did have some cached sample. The styling actually works. What about the pinning to the bottom in the pinning-options sample?

2023-12-15 14:18 UTC, MayaKirova commented
@mddragnev It seems to be the same for the base grid sample:https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/row-pinning#web-components-grid-row-pinning-example

Might be an issue with the property editor itself since setting the value via the enum initially or runtime works fine (sets it as number 0/1), while the editor seems to set it as string ("top"/"bottom") hence it doesn't work.

2023-12-15 15:47 UTC, mddragnev commented
Okay, logged an issue: https://github.com/IgniteUI/igniteui-xplat-examples/issues/452

2023-12-15 15:47 UTC, mddragnev approved these changes

2024-01-09 16:21 UTC, dkamburov commented
@MayaKirova, @mddragnev Are we ready to merge this?

2024-01-10 08:36 UTC, MayaKirova commented
> @MayaKirova, @mddragnev Are we ready to merge this?

@dkamburov Yes.

2024-01-10 15:42 UTC, dkamburov commented
> > @MayaKirova, @mddragnev Are we ready to merge this?
> 
> @dkamburov Yes.

Can you also approve it?

2024-01-10 15:43 UTC, MayaKirova approved these changes

2024-01-11 09:45 UTC, merged