Update sample to use Paginator instead of deprecated paging prop. Als…
IgniteUI/igniteui-xplat-examples pull request #253
Opened 2023-06-29 10:15 UTC by MayaKirova

…o remove unnecessary cols.

Related to:https://github.com/IgniteUI/igniteui-xplat-docs/pull/853

2023-12-06 09:51 UTC, IMinchev64 requested changes

2023-12-06 09:51 UTC, IMinchev64 commented on samples/grids/tree-grid/overview.json
> +    "WebPaginatorModule"
This is incorrectly generated as IgbWebPaginatorModule and IgrWebPaginatorModule in Blazor and React samples , while they should be IgbPaginatorModule and IgrPaginatorModule respectively.

2023-12-07 15:00 UTC, MayaKirova commented on samples/grids/tree-grid/overview.json
> +    "WebPaginatorModule"
@IMinchev64 Should generate correct now.

2023-12-07 15:34 UTC, IMinchev64 approved these changes

2023-12-07 21:49 UTC, merged