Add tgrid row editing samples
IgniteUI/igniteui-xplat-examples pull request #256
Opened 2023-07-03 10:18 UTC by onlyexeption

2023-07-05 09:14 UTC, MayaKirova requested changes

2023-07-05 09:14 UTC, MayaKirova commented on samples/grids/tree-grid/row-editing-options.json
> +{
I think this second sample description was added by mistake, there should be just 1 main code block.

2023-07-06 17:17 UTC, HUSSAR-mtrela commented on samples/grids/tree-grid/row-editing-options.json
> +{
@onlyexeption can you fix the sample (see above)

2023-07-07 07:26 UTC, MayaKirova approved these changes

2023-10-13 13:28 UTC, merged