mdd-format-specifiers
IgniteUI/igniteui-xplat-examples pull request #282
Opened 2023-08-23 20:30 UTC by mddifilippo89

mdd-format-specifiers

2023-08-24 15:21 UTC, HUSSAR-mtrela requested changes
@mddifilippo89 can you add FinChart sample with format specifiers which should be similar to CC sample?

2023-08-25 19:06 UTC, HUSSAR-mtrela requested changes

2023-08-25 19:06 UTC, HUSSAR-mtrela commented on samples/charts/category-chart/format-specifiers.json
> +      "orientation": "Horizontal"
change legend type to DataLegend and set
      "valueFormatMode": "Currency",
      "valueFormatString": "${0} Billion",

2023-08-25 19:06 UTC, HUSSAR-mtrela commented on samples/charts/category-chart/format-specifiers.json
> +    "charts/LegendModule",
used DataLegendModule

2023-08-25 19:06 UTC, HUSSAR-mtrela commented on samples/charts/data-chart/format-specifiers.json
> +      "orientation": "Horizontal"
change legend type to DataLegend and set
"valueFormatMode": "Currency",
"valueFormatString": "${0} Billion",

2023-09-08 20:09 UTC, mddifilippo89 commented on samples/charts/category-chart/format-specifiers.json
> +      "orientation": "Horizontal"
done

2023-09-08 20:09 UTC, mddifilippo89 commented on samples/charts/category-chart/format-specifiers.json
> +    "charts/LegendModule",
updated

2023-09-08 20:11 UTC, mddifilippo89 commented on samples/charts/data-chart/format-specifiers.json
> +      "orientation": "Horizontal"
done

2023-09-08 20:14 UTC, HUSSAR-mtrela approved these changes

2023-09-08 20:14 UTC, merged