fix(react): add placeholders for templates in react app template
IgniteUI/igniteui-xplat-examples pull request #283
Opened 2023-08-24 14:44 UTC by dkamburov

2023-08-25 07:27 UTC, MayaKirova requested changes

2023-08-25 07:27 UTC, MayaKirova commented on code-gen-library/WebGridGroupByRowTemplate/React.tsx
> +    public webGridGroupByRowTemplate = (ctx: IgcGroupByRowTemplateContext) => {
Shouldn't IgcGroupByRowTemplateContext have an Igr prefix?

2023-08-25 07:27 UTC, MayaKirova commented on code-gen-library/WebGridGroupByRowTemplate/React.tsx
> +            <igc-badge>${groupRow.records.length}</igc-badge>
This should probably be `IgrBadge` instead.

2023-08-25 13:30 UTC, MayaKirova approved these changes

2023-08-28 14:50 UTC, HUSSAR-mtrela requested changes

2023-08-28 14:50 UTC, HUSSAR-mtrela commented on editor-templates/React/main-template/src/index.tsx
> +import 'igniteui-react-grids/grids/themes/light/bootstrap.css';
wouldn't this change force chart samples that use editor component to depend on the grids package?

2023-08-28 15:07 UTC, dkamburov commented on editor-templates/React/main-template/src/index.tsx
> +import 'igniteui-react-grids/grids/themes/light/bootstrap.css';
I guess so, but wasn't it like up until now?

2023-08-28 15:09 UTC, dkamburov commented on editor-templates/React/main-template/src/index.tsx
> +import 'igniteui-react-grids/grids/themes/light/bootstrap.css';
Oh or we need those styles for the editor components

2023-09-07 08:10 UTC, ChronosSF commented
@HUSSAR-mtrela , please review again so we can merge this. Thank you!

2023-09-07 11:47 UTC, MayaKirova commented
@HUSSAR-mtrela @ChronosSF I've run a pipeline from this branch and all imports in the generated grid samples look good: https://infragistics.visualstudio.com/NetAdvantage/_build/results?buildId=111118&view=artifacts&pathAsName=false&type=publishedArtifacts

Should we also bump up the package versions to the beta 18.2.2-beta.0 since that's the first release package that has the grid or should we wait for the official release?

2023-09-11 22:33 UTC, HUSSAR-mtrela approved these changes

2023-09-11 22:34 UTC, merged