Add WebGridCurrencyCellTemplate for React
IgniteUI/igniteui-xplat-examples pull request #316
Opened 2023-09-27 08:02 UTC by IMinchev64

2023-09-29 14:59 UTC, MayaKirova requested changes

2023-09-29 14:59 UTC, MayaKirova commented on code-gen-library/WebGridCurrencyCellTemplate/React.ts
> +<!--begin styles-->
I don't think these classes are used in the template. They can probably be skipped or set instead of the inline styles.

2023-10-03 10:21 UTC, MayaKirova requested changes

2023-10-03 10:21 UTC, MayaKirova commented on code-gen-library/WebGridCurrencyCellTemplate/React.ts
> +                <IgrBadge variant="success" className="badge-left"><span>▲</span></IgrBadge>
Setting className on the Badge does not seem to work as it does not get set as class on the underlaying element:
![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/10397980/a5e8faa6-34d1-4e31-9871-fa9c03100f07)
That seems like a bug.
I guess you can either wrap the badge in a div that has className or set the style inline as it was to have it work for the sample.

2023-10-03 19:05 UTC, gmurray81 commented on code-gen-library/WebGridCurrencyCellTemplate/React.ts
> +                <IgrBadge variant="success" className="badge-left"><span>▲</span></IgrBadge>
was the issue here the extra container? I think we have those in Blazor atm too. Ideally they wouldn't be present, but sometimes we need them for the portaling we are doing. Does it behave differently if you set display: contents on the extra conttainer?

2023-10-04 07:28 UTC, MayaKirova commented on code-gen-library/WebGridCurrencyCellTemplate/React.ts
> +                <IgrBadge variant="success" className="badge-left"><span>▲</span></IgrBadge>
@gmurray81 The extra containers are fine. It's just that the the `className` prop set on the badge does not become `class` when rendered in the dom, while it renders fine for a simple div. So that class does not actually get applied.

2023-10-04 11:13 UTC, gmurray81 commented on code-gen-library/WebGridCurrencyCellTemplate/React.ts
> +                <IgrBadge variant="success" className="badge-left"><span>▲</span></IgrBadge>
Ah, we need to adjust the wrapper gen so that className is replicated to the inner component then, but as class.

2023-10-04 11:15 UTC, gmurray81 commented on code-gen-library/WebGridCurrencyCellTemplate/React.ts
> +                <IgrBadge variant="success" className="badge-left"><span>▲</span></IgrBadge>
Could work around it too of course, but we should def fix that soon

2023-10-04 12:24 UTC, MayaKirova commented on code-gen-library/WebGridCurrencyCellTemplate/React.ts
> +                <IgrBadge variant="success" className="badge-left"><span>▲</span></IgrBadge>
Logged it here: https://infragistics.visualstudio.com/NetAdvantage/_workitems/edit/27156
I think it's fine to use a workaround for now so we don't hold up the samples.

2023-10-04 12:30 UTC, MayaKirova approved these changes

2023-10-04 12:44 UTC, merged