Update templates for composite binding data and nested data samples
IgniteUI/igniteui-xplat-examples pull request #398
Opened 2023-10-19 14:03 UTC by mddragnev

closing #392

2023-10-20 14:21 UTC, HUSSAR-mtrela requested changes

2023-10-20 14:21 UTC, HUSSAR-mtrela commented on code-gen-library/WebGridCompositeAddressEditCellTemplate/WebComponents.ts
> +                </div>`;
shouldn't there be import for IgcInputComponent like you do in React?

2023-10-20 14:21 UTC, HUSSAR-mtrela commented on code-gen-library/WebGridCompositeContactEditCellTemplate/WebComponents.ts
> +                </div>`;
shouldn't there be import for IgcInputComponent like you do in React?

2023-10-23 11:11 UTC, mddragnev commented on code-gen-library/WebGridCompositeAddressEditCellTemplate/WebComponents.ts
> +                </div>`;
No, they dont need importing neither in WC nor in Blazor

2023-10-23 11:12 UTC, mddragnev commented on code-gen-library/WebGridCompositeContactEditCellTemplate/WebComponents.ts
> +                </div>`;
No, they dont need importing neither in WC nor in Blazor

2023-10-24 21:57 UTC, HUSSAR-mtrela approved these changes

2023-10-26 16:06 UTC, HUSSAR-mtrela approved these changes

2023-10-30 09:29 UTC, merged