Add tree grid hide and pin first group templates. Some minor fixes.
IgniteUI/igniteui-xplat-examples pull request #404
Opened 2023-10-23 13:57 UTC by skrustev

Resolves #399

2023-10-25 15:23 UTC, HUSSAR-mtrela approved these changes

2023-10-25 15:25 UTC, HUSSAR-mtrela commented
@skrustev please change convert this draft PR to full PR if ready because we need to have this fix for the critical issue

2023-10-27 10:53 UTC, mddragnev requested changes

2023-10-27 10:53 UTC, mddragnev commented on code-gen-library/WebTreeGridHideFirstGroupToggle/Blazor.cs
> +        var columnGroup = this.grid.ActualColumns[1];
this.grid should be either this.treeGrid or a getDescription method to correctly extract the grid instance

2023-10-27 10:53 UTC, mddragnev commented on code-gen-library/WebTreeGridPinFirstGroupToggle/Blazor.cs
> +        var columnGroup = this.grid.ActualColumns[1];
this.grid should be either this.treeGrid or a getDescription method to correctly extract the grid instance

2023-10-30 09:23 UTC, mddragnev approved these changes

2023-10-30 11:46 UTC, merged