Added CellEditing samples,data and templates
IgniteUI/igniteui-xplat-examples pull request #507
Opened 2024-03-06 22:16 UTC by tishko0

2024-04-05 12:11 UTC, IMinchev64 commented
I am currently playing around with the generated React sample from this configuration and several things seem to not work.

Some errors are coming from the `webGridCellEditCellTemplate`:
- the call to `this.grid1` as there is no `grid1` generated but rather `hierarchicalGrid1` in the sample.
- use of attribute `textContext` in `IgrSelectItem` gives:
```
Type '{ selected: boolean; textContent: any; value: any; key: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<IgrSelectItem> & Readonly<IIgrSelectItemProps>'.
  Property 'textContent' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<IgrSelectItem> & Readonly<IIgrSelectItemProps>'.
```

- use of `size` property in `IgrSelect` gives:
```
Type '{ children: any; size: string; key: string; change: (x: any) => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<IgrSelect> & Readonly<IIgrSelectProps>'.
  Property 'size' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<IgrSelect> & Readonly<IIgrSelectProps>'.
```

Finally, the row islands in the sample show no data for some reason.

I am using igniteui-react version 18.6.0 for testing.

2024-04-09 06:53 UTC, tishko0 commented
Not really sure where size and textContext were coming from, they were not in the templates so, but  the templates were used in the flat grid as well, so might have been causing it. I added new templates so it should be running okay now.

2024-04-09 14:54 UTC, IMinchev64 requested changes
When you generate the cell-editing-styling samples for WC, React, and Blazor the custom styling is generated but not applied.

2024-04-09 14:54 UTC, IMinchev64 commented on samples/grids/hierarchical-grid/editing-events.json
> +        "cellEditRef": "WebGridEditingEventsCellEdit",
The `WebGridEditingEventsCellEdit` template does not correspond to `SingersData`.

2024-04-10 16:17 UTC, tishko0 commented
> When you generate the cell-editing-styling samples for WC, React, and Blazor the custom styling is generated but not applied.

added id to grid so styles should display properly now

2024-04-10 16:20 UTC, tishko0 commented on samples/grids/hierarchical-grid/editing-events.json
> +        "cellEditRef": "WebGridEditingEventsCellEdit",
fixed the data, but the cellEditRef property is not property of rowIslands so I have it added on the main grid for now only.

2024-04-12 09:35 UTC, IMinchev64 approved these changes

2024-04-12 11:37 UTC, merged