Add hgrid editing samples
IgniteUI/igniteui-xplat-examples pull request #536
Opened 2024-03-21 13:54 UTC by georgianastasov

2024-04-04 21:49 UTC, tishko0 commented
Works fine for WC but loads as plain grid for Blazor for some reason. Maybe needs further re-templating of the renderer as the execution sequence is not present as well. Also can you please add react templates.

2024-04-04 21:50 UTC, tishko0 requested changes
Please add React templates and review Blazor output

2024-04-05 11:08 UTC, georgianastasov commented
Removed cellEditDoneRef from Hierarchical Grid and Row Island due to lack of implementation in Blazor and incompatibility with React.

2024-04-08 06:44 UTC, tishko0 approved these changes

2024-04-09 07:18 UTC, merged