Add HierarchicalGrid row pinning samples
IgniteUI/igniteui-xplat-examples pull request #539
Opened 2024-03-22 16:03 UTC by MonikaKirkova

2024-04-09 11:12 UTC, tishko0 requested changes

2024-04-09 11:12 UTC, tishko0 commented on code-gen-library/WebHierarchicalGridChangePinningConfig/Web.ts
> +        rowIsland1.pinning = pinningConfig;
IgrRowIslandComponent is a react component which is not an extension of HTML Element. This cast will not work in React as the objects are not of the same type, and typescript will not like it.
In React we use reference instead, so  we would like to do something like this we will need to create a ref object first:
var rowIsland1 = createRef<IgrRowIsland>();
and then in the html to add the reference
<IgrRowIsland ref = {this.rowIsland1} </IgrRowIsland>
and finally we can call it:
rowisland1.current.pinning = pinningConfig;

However,  the xplat editor does not currently create refs for rowIslands, but it does for the grid, so you can use that and access the data collection to get the rowIsland.
You can do something like:
var island1 = this.hierarchicalGrid.childLayoutList.filter(e => e.childDataKey == ' Albums');
island[0].pinning = pinnningConfig;
Can you please add such a template for React plaese.

2024-04-09 11:12 UTC, tishko0 commented on code-gen-library/WebHierarchicalGridPinRowOnRendered/Web.ts
> +		hierarchicalGrid.pinRow(this.singersData[0].Photo);
Same as the previous, react elements are not part of the dom, but there is already a reference for the grid that React provides, so just make a react only template that can look like this:

public webHierarchicalGridPinRowOnRendered(): void {
        this.hierarchicalGrid.pinRow(this.singersData[0].Photo);
        this.hierarchicalGrid.pinRow(this.singersData[1].Photo);
    }

In regards to the above, this template is used in 2 samples, and you have a reference to the grid as ' 
'hierarchicalGrid' in the first one, and just as 'grid' in the 2nd one, so you will have to make the reference to be the same in both samples or one will always throw an error.

2024-04-15 07:29 UTC, tishko0 approved these changes

2024-04-15 14:23 UTC, MayaKirova commented
@tishko0 Is this verified? If so update the tag.

2024-04-16 10:10 UTC, merged