Add hgrid cell selection samples
IgniteUI/igniteui-xplat-examples pull request #577
Opened 2024-04-12 12:11 UTC by MayaKirova

Reopening the PR since it broke sample gen with error: 

```
CodeGenLib: d:/work/agenta/_work/29/s/igniteui-xplat-examples/code-gen-library/WebHierarchicalGridCellSelectionStyling/Blazor.js MISSING: 'public WebHierarchicalGridCellSelectionStyling' string in igRegisterScript call
CodeGenLib: d:/work/agenta/_work/29/s/igniteui-xplat-examples/code-gen-library/WebHierarchicalGridCellSelectionStyling/Web.ts MISSING: 'class WebHierarchicalGridCellSelectionStyling' in pascal case
CodeGenLib: d:/work/agenta/_work/29/s/igniteui-xplat-examples/code-gen-library/WebHierarchicalGridCellSelectionStyling/Web.ts MISSING: 'public webHierarchicalGridCellSelectionStyling' function in camel case
>> CodeGenLibrary verification: failed

```

@IvanKitanov17 please fix it.
@tishko0 Please test it for real.

2024-04-12 15:51 UTC, tishko0 requested changes
I can't really find any samples using those templates? Were they supposed to be used in samples/grids/hierarchical-grid/cell-selection-styling.json?

2024-04-12 15:58 UTC, MayaKirova commented
@tishko0 Did you fetch and pull the latest changes?

2024-04-12 16:07 UTC, MayaKirova commented
> @tishko0 Did you fetch and pull the latest changes?

Ah, nevermind it is indeed missing from the sample.

2024-04-12 20:25 UTC, mddifilippo89 approved these changes

2024-04-13 14:41 UTC, mddifilippo89 commented
@tishko0 @MayaKirova 
please approve this and close https://github.com/IgniteUI/igniteui-xplat-examples/pull/577
Then we can queue up the igniteui-xplat-examples-output+PRs build so it pushes an update angular-examples so we can fix the samples browsers.

2024-04-15 07:25 UTC, MayaKirova commented
@mddifilippo89 No. The samples are not actually fully functional.
You may merge the revert of the original incorrectly merged change from here if you wish a quick fix: https://github.com/IgniteUI/igniteui-xplat-examples/pull/576

2024-04-15 10:42 UTC, tishko0 requested changes

2024-04-15 10:42 UTC, tishko0 commented on samples/grids/hierarchical-grid/cell-selection-overview.json
> +      "targetRef": "grid",
this is throwing compilation error as it is not consistent with the ref of the grid. In this case since there is no name defined for the grid it defaults for hierarchicalGrid1.

2024-04-15 10:42 UTC, tishko0 commented on samples/grids/hierarchical-grid/cell-selection-styling.json
> +      "targetRef": "grid",
Same as the other sample, no target grid defined below

2024-04-15 13:56 UTC, tishko0 requested changes
@MayaKirova The third nested collection is not generating for Blazor, so all Songs grids are empty. I don't really find it okay, but it generates for the rest of the platforms. Should we avoid nesting so deep in the samples?

2024-04-15 13:56 UTC, tishko0 commented on samples/grids/hierarchical-grid/cell-selection-styling.json
>        "onInit": ["WebHierarchicalGridCellSelectionStyling"],
onInit is not a property of the grid. Are styles loading for you???
Also, while fixing this, please update the css properties to be like
--ig-grid-cell-selected-text-color: #FFFFFF;
because when they are just:
--cell-selected-text-color: #FFFFFF;
they don't apply to the subgrids

2024-04-15 14:49 UTC, MayaKirova commented on samples/grids/hierarchical-grid/cell-selection-styling.json
>        "onInit": ["WebHierarchicalGridCellSelectionStyling"],
You should tag @IvanKitanov17, so he can reflect the changes.

2024-04-15 15:24 UTC, MayaKirova commented
> @MayaKirova The third nested collection is not generating for Blazor, so all Songs grids are empty. I don't really find it okay, but it generates for the rest of the platforms. Should we avoid nesting so deep in the samples?

No, you should not avoid nesting. If it does not work it's either an issue with the sample (you can check the generated sample and see if anything is missing) or a bug in Blazor.

2024-04-16 08:19 UTC, tishko0 approved these changes

2024-04-16 10:10 UTC, merged