Add TreeGrid toolbar samples
IgniteUI/igniteui-xplat-examples pull request #584
Opened 2024-04-16 08:18 UTC by RivaIvanova

2024-05-30 15:02 UTC, tishko0 requested changes
Sample 1 and 2 are absolutely the same. There is no reason to add the same sample second time. The angular sample have a control panel adding the features dynamically. Please delete the second sample and we will add custom one instead as the one in angular. 
Also no sample have toolbar title applied to it, while there are snippets with it in the topic. I think we should include it.
Regarding the styling sample, the styles do not seem to apply in Blazor. Can you check them and maybe add styling for the title as it defaults in orange and currently the sample is setting the rest of the buttons in blue

2024-06-03 05:39 UTC, RivaIvanova commented
@tishko0 The first and second samples are the same since I followed the same approach which is for the [grid](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/toolbar#features) and [hierarchical grid](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/hierarchical-grid/toolbar#features) where no dynamic change of the features is included due to the igEditor not allowing it. I could create a custom sample, but I think a separate task should be logged for the other grids as well in order for them to be aligned.

For the toolbar title, again, none of the grid or hierarchical grid samples have a toolbar title applied (apart from the [Exporting Indicator](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/hierarchical-grid/toolbar#exporting-indicator) and [Custom Content](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/hierarchical-grid/toolbar#custom-content) samples for the hierarchical grid) since currently, the igEditor does not seem to allow this configuration. From what I can see, in order to apply it, all samples should be custom samples as I couldn't find a way to configure it via the editor. Can you confirm if this is the case?

Regarding the styling sample, I used the predefined [`WebGridToolbarStyleWithCustomCSS`](https://github.com/IgniteUI/igniteui-xplat-examples/tree/23.2.x/code-gen-library/WebGridToolbarStyleWithCustomCSS) and on my side, the styles are applied as expected compared to the other grid's styling demos - [grid](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/toolbar#demo), [hierarchical grid](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/hierarchical-grid/toolbar#demo).
![tree-grid-blazor-style](https://github.com/IgniteUI/igniteui-xplat-examples/assets/49126110/17443e82-b626-4e55-8896-45d4e94caf2f)

ATM only the toolbar background and export button dropdown background is set. The `--ig-grid-toolbar-title-text-color: #ffcd0f;` configuration seems unnecessary because no toolbar title is being present due to the igEditor. I can create a custom sample where the title and its custom styling are set, but again, maybe this should be logged for the other grids as well. What do you think?

2024-06-03 12:16 UTC, RivaIvanova commented
@tishko0 I removed the `toolbar-sample-2` sample and created a custom one for each platform - [WC](https://github.com/IgniteUI/igniteui-wc-examples/pull/734), [React](https://github.com/IgniteUI/igniteui-react-examples/pull/546), and [Blazor](https://github.com/IgniteUI/igniteui-blazor-examples/pull/706).

2024-06-04 11:02 UTC, tishko0 approved these changes

2024-06-05 13:24 UTC, merged