Update package.json
IgniteUI/igniteui-xplat-examples pull request #614
Opened 2024-05-17 15:00 UTC by mddifilippo89

2024-05-17 15:18 UTC, HUSSAR-mtrela approved these changes

2024-05-17 15:19 UTC, HUSSAR-mtrela requested changes
ok hold until PR is merged in the SB

2024-05-23 14:59 UTC, HUSSAR-mtrela requested changes
update blazor template to 23.2.218 version

2024-05-23 15:01 UTC, mddifilippo89 commented
> update blazor template to 23.2.218 version

https://github.com/IgniteUI/igniteui-xplat-examples/pull/614/commits/046d42833a3e4db4556b7e50e0048343b232de87

2024-05-23 15:09 UTC, HUSSAR-mtrela approved these changes

2024-05-23 15:09 UTC, merged