mdd-use-codegenhelper-toolbar-icon
IgniteUI/igniteui-xplat-examples pull request #636
Opened 2024-06-11 21:41 UTC by mddifilippo89

mdd-use-codegenhelper-toolbar-icon

2024-06-12 02:29 UTC, gmurray81 requested changes

2024-06-12 02:29 UTC, gmurray81 commented on code-gen-library/ToolbarCustomIconOnViewInit/Angular.ts
> +	const toolbar = CodeGenHelper.GetDescription<IgxToolbar>("content");
I think this would be IgxToolbarComponent right?

2024-06-12 02:29 UTC, gmurray81 commented on code-gen-library/ToolbarCustomIconOnViewInit/Angular.ts
> +	const toolbar = CodeGenHelper.GetDescription<IgxToolbar>("content");
and this would be aboveLeftContent, right? Could you actually check these in the editor plz?

2024-06-12 02:29 UTC, gmurray81 commented on code-gen-library/ToolbarCustomIconOnViewInit/Angular.ts
> +	const toolbar = CodeGenHelper.GetDescription<IgxToolbar>("content");
Or is this a scenario where the toolbar is the hero component in content?

2024-06-12 02:29 UTC, gmurray81 commented on code-gen-library/ToolbarCustomIconOnViewInit/Angular.ts
> +	const toolbar = CodeGenHelper.GetDescription<IgxToolbar>("content");
anyhow also check WC for needing a Component suffix also.

2024-06-12 14:55 UTC, mddifilippo89 commented on code-gen-library/ToolbarCustomIconOnViewInit/Angular.ts
> +	const toolbar = CodeGenHelper.GetDescription<IgxToolbar>("content");
I pushed another commit with the correct component names

2024-06-18 16:36 UTC, agoldenbaum approved these changes

2024-07-15 17:25 UTC, HUSSAR-mtrela approved these changes

2024-07-15 17:26 UTC, merged