grid pager sample
IgniteUI/igniteui-xplat-examples pull request #68
Opened 2022-10-20 17:56 UTC by igMPeterson

2022-10-20 22:45 UTC, HUSSAR-mtrela requested changes

2022-10-20 22:45 UTC, HUSSAR-mtrela commented on samples/grids/grid/grid-pager-sample.txt
> +TODO Ability to hide Page Buttons (First, Prev, Next, Last)
now, you can add TODO notes in the beginning of JSON file:
```
{
  "todo": [ 
     "reminder to do item 1",
     "reminder to do item 2" 
  ],
  "descriptions": { 
  }
  
  ```

2022-10-20 22:45 UTC, HUSSAR-mtrela commented on samples/grids/grid/grid-pager-sample.json
> +  "WebGridModule"
use "grids/WebGridModule"

2022-10-21 13:46 UTC, igMPeterson commented on samples/grids/grid/grid-pager-sample.json
> +  "WebGridModule"
update to use proper module

2022-10-21 14:34 UTC, HUSSAR-mtrela approved these changes

2022-10-21 14:34 UTC, merged