Changed colors for row-editing-styles sample
IgniteUI/igniteui-xplat-examples pull request #736
Opened 2024-10-15 09:58 UTC by MarielaTihova

Closes #729

2024-10-25 10:09 UTC, MayaKirova requested changes

2024-10-25 10:09 UTC, MayaKirova commented on code-gen-library/WebGridRowEditingStyle/Blazor.js
> +    color: #ffcd0f;
You could use css vars for the button to style them rather than targeting the DOM element directly. The vars are named the same as in Angular, prefixed with ig-{componentName}, so something like:

```
#grid {
    --ig-button-foreground: #ffcd0f;
    --ig-button-hover-foreground: white;
}
```

2024-10-30 14:09 UTC, dkamburov commented on code-gen-library/WebGridRowEditingStyle/Blazor.js
> +    color: #ffcd0f;
@MarielaTihova just to remaind you about this :)

2024-10-30 14:10 UTC, MayaKirova approved these changes

2024-10-31 13:03 UTC, MarielaTihova commented on code-gen-library/WebGridRowEditingStyle/Blazor.js
> +    color: #ffcd0f;
Already committed changes @dkamburov

2024-11-01 11:57 UTC, merged