updates for samples testing
IgniteUI/igniteui-xplat-examples pull request #742
Opened 2024-10-23 19:12 UTC by IGvaleries

2024-10-23 21:47 UTC, gmurray81 requested changes

2024-10-23 21:47 UTC, gmurray81 commented on code-gen-library/ChartStyleTest/WPF.cs
> -    //WPF: System.Action
I'm not sure it's a good idea to remove these since the editor still wants them. Unless you adjusted the editor?

2024-10-25 14:47 UTC, IGvaleries commented on code-gen-library/ChartStyleTest/WPF.cs
> -    //WPF: System.Action
added back in the handler types

2024-10-29 00:15 UTC, gmurray81 approved these changes

2024-10-29 13:53 UTC, merged